<script src="{{ asset('admin/app-assets/vendors/js/vendors.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/app-assets/vendors/js/charts/chartist.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/app-assets/vendors/js/charts/chartist-plugin-tooltip.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/app-assets/vendors/js/charts/raphael-min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/app-assets/vendors/js/charts/morris.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/app-assets/vendors/js/timeline/horizontal-timeline.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/app-assets/js/core/app-menu.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/app-assets/js/core/app.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/app-assets/js/scripts/customizer.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/app-assets/js/scripts/pages/dashboard-ecommerce.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/app-assets/js/my-script.js') }}" type="text/javascript"></script>